clear;
load averageVz.dat;
load averageVz0.dat;
load averageVz1.dat;
load averageVz2.dat;
load averageVz3.dat;
load averageVz4.dat;
load averageVz5.dat;
load averageVz6.dat;
load averageVz7.dat;
load averageVz8.dat;
load averageVz9.dat;
N1=1;
N2=100;
figure(1);
plot (averageVz0(1:N2,1),averageVz0(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(2);
plot (averageVz1(1:N2,1),averageVz1(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(3);
plot (averageVz2(1:N2,1),averageVz2(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(4);
plot (averageVz3(1:N2,1),averageVz3(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(5);
plot (averageVz4(1:N2,1),averageVz4(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(6);
plot (averageVz5(1:N2,1),averageVz5(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(7);
plot (averageVz6(1:N2,1),averageVz6(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(8);
plot (averageVz7(1:N2,1),averageVz7(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(9);
plot (averageVz8(1:N2,1),averageVz8(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(10);
plot (averageVz9(1:N2,1),averageVz9(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;
figure(11);
plot (averageVz(1:N2,1),averageVz(1:N2,2),'blue');
title ('average vz p > p0');
xlabel ('p');
ylabel ('Vz');
grid ;