clear;
load tamc_shock_wave.dat;
N1=1;
N2=50;
!particle_count(1:N2,1:3)= 0;
!for j=1:N2,
!    particle_count(j,1) = tamc_particle_count(2*j,1);
!    particle_count(j,2) = tamc_particle_count(2*j,2);
!end;
figure(1);
plot (tamc_shock_wave(1:N2,1),tamc_shock_wave(1:N2,2),'blue');
title ('shock wawe r');
xlabel ('iteration');
ylabel ('r');
grid ;
figure(2);
plot (tamc_shock_wave(1:N2,1),tamc_shock_wave(1:N2,3),'blue');
title ('shock wawe velocity');
xlabel ('iteration');
ylabel ('U');
grid ;