clear;
load extra_iterations.dat;
N = size(extra_iterations,1);
figure(1);
plot (extra_iterations(1:N,1),extra_iterations(1:N,3),'red');
title ('mass');
xlabel ('ieration');
ylabel ('m g');
grid ;
figure(2);
plot (extra_iterations(1:N,1),extra_iterations(1:N,4),'red');
title ('momentum');
xlabel ('ieration');
ylabel ('p g*cm/s');
grid ;
figure(3);
plot (extra_iterations(1:N,1),extra_iterations(1:N,5),'red');
title ('energy');
xlabel ('ieration');
ylabel ('e erg');
grid ;
figure(4);
plot (extra_iterations(1:N,1),extra_iterations(1:N,6),'red');
title ('kinetic energy');
xlabel ('ieration');
ylabel ('e erg');
grid ;
figure(5);
plot (extra_iterations(1:N,1),extra_iterations(1:N,7),'red');
title ('termal energy');
xlabel ('ieration');
ylabel ('e erg');
grid ;