clear;
load iterations.dat;
year = 3.15*10^7;
N = size(iterations,1);
figure(1);
plot (iterations(1:N,2)/year,iterations(1:N,3),'red');
title ('mass');
xlabel ('time year');
ylabel ('m g');
grid ;
figure(2);
plot (iterations(1:N,2)/year,iterations(1:N,4),'red');
title ('momentum');
xlabel ('time year');
ylabel ('p g*cm/s');
grid ;
figure(3);
plot (iterations(1:N,2)/year,iterations(1:N,5),'red');
title ('energy');
xlabel ('time year');
ylabel ('e erg');
grid ;
figure(4);
plot (iterations(1:N,2)/year, iterations(1:N,6), 'blue', iterations(1:N,2)/year, iterations(1:N,7),'red');
legend('injected','evaluated',4);
title ('particles');
xlabel ('time year');
ylabel ('N count');
grid ;
