clear;
load iterations.dat;
N = size(iterations,1);
figure(1);
plot (iterations(1:N,1),iterations(1:N,3),'red');
title ('mass');
xlabel ('ieration');
ylabel ('m g');
grid ;
figure(2);
plot (iterations(1:N,1),iterations(1:N,4),'red');
title ('momentum');
xlabel ('ieration');
ylabel ('p g*cm/s');
grid ;
figure(3);
plot (iterations(1:N,1),iterations(1:N,5),'red');
title ('energy');
xlabel ('ieration');
ylabel ('e erg');
grid ;