clear;
load tamc_radial_profile.dat;
N1=1;
N2=100;
N3=6;
e = size(tamc_radial_profile,1)/N2 - 1;
d = fix(3*e/4);
c = fix(e/2);
b = fix(e/4);
a = 5;
r(1:N2,1:N3) = 0;
pressure(1:N2,1:N3 + 1) = 0;
crpressure(1:N2,1:N3 + 1) = 0;
summpressure(1:N2,1:N3 + 1) = 0;
for j=1:N2,
    r(j,1) = tamc_radial_profile(j,1);
    r(j,2) = tamc_radial_profile(a*N2 + j,1);
    r(j,3) = tamc_radial_profile(b*N2 + j,1);
    r(j,4) = tamc_radial_profile(c*N2 + j,1);
    r(j,5) = tamc_radial_profile(d*N2 + j,1);
    r(j,6) = tamc_radial_profile(e*N2 + j,1);
    pressure(j,1)=tamc_radial_profile(j,1);
    pressure(j,2)=tamc_radial_profile(j,4);
    pressure(j,3)=tamc_radial_profile(a*N2 + j,4);
    pressure(j,4)=tamc_radial_profile(b*N2 + j,4);
    pressure(j,5)=tamc_radial_profile(c*N2 + j,4);
    pressure(j,6)=tamc_radial_profile(d*N2 + j,4);
    pressure(j,7)=tamc_radial_profile(e*N2 + j,4);       
    crpressure(j,1)=tamc_radial_profile(j,1);
    crpressure(j,2)=tamc_radial_profile(j,5);
    crpressure(j,3)=tamc_radial_profile(a*N2 + j,5);
    crpressure(j,4)=tamc_radial_profile(b*N2 + j,5);
    crpressure(j,5)=tamc_radial_profile(c*N2 + j,5);
    crpressure(j,6)=tamc_radial_profile(d*N2 + j,5);
    crpressure(j,7)=tamc_radial_profile(e*N2 + j,5);
    summpressure(j,1)=tamc_radial_profile(j,1);
    summpressure(j,2)=pressure(j,2) + crpressure(j,2);
    summpressure(j,3)=pressure(j,3) + crpressure(j,3);
    summpressure(j,4)=pressure(j,4) + crpressure(j,4);
    summpressure(j,5)=pressure(j,5) + crpressure(j,5);
    summpressure(j,6)=pressure(j,6) + crpressure(j,6);
    summpressure(j,7)=pressure(j,7) + crpressure(j,7);     
end;
figure(1);
plot (r(1:N2,1),pressure(1:N2,2),'cyan',r(1:N2,2),pressure(1:N2,3),'green',r(1:N2,3),pressure(1:N2,4),'blue',r(1:N2,4),pressure(1:N2,5),'black',r(1:N2,5),pressure(1:N2,6),'yellow',r(1:N2,6),pressure(1:N2,7),'red');
title ('pressure');
xlabel ('r cm');
ylabel ('P din/cm^2');
grid ;
figure(2);
plot (r(1:N2,1),crpressure(1:N2,2),'cyan',r(1:N2,2),crpressure(1:N2,3),'green',r(1:N2,3),crpressure(1:N2,4),'blue',r(1:N2,4),crpressure(1:N2,5),'black',r(1:N2,5),crpressure(1:N2,6),'yellow',r(1:N2,6),crpressure(1:N2,7),'red');
title ('cosnic ray pressure');
xlabel ('r cm');
ylabel ('P din/cm^2');
grid;
figure(3);
plot (r(1:N2,1),summpressure(1:N2,2),'cyan',r(1:N2,2),summpressure(1:N2,3),'green',r(1:N2,3),summpressure(1:N2,4),'blue',r(1:N2,4),summpressure(1:N2,5),'black',r(1:N2,5),summpressure(1:N2,6),'yellow',r(1:N2,6),summpressure(1:N2,7),'red');
title ('summ pressure');
xlabel ('r cm');
ylabel ('P din/cm^2');
grid ;