clear;
load zprofile.dat;
N1=1;
N2=4000;
N3=6;
rmin = 200;
e = size(zprofile,1)/N2 - 1;
d = fix(3*e/4);
c = fix(e/2);
b = fix(e/4);
a = 5;
radius(1:N2,1:N3) = 0;
vel(1:N2,1:N3 + 1)= 0;
rho(1:N2,1:N3 + 1) = 0;
pressure(1:N2,1:N3 + 1) = 0;
temp(1:N2,1:N3 + 1) = 0;
for j=1:N2,
    radius(j,1)=zprofile(j,1);
    radius(j,2)=zprofile(a*N2 + j,1);
    radius(j,3)=zprofile(b*N2 + j,1);
    radius(j,4)=zprofile(c*N2 + j,1);
    radius(j,5)=zprofile(d*N2 + j,1);
    radius(j,6)=zprofile(e*N2 + j,1);
    vel(j,1)=zprofile(j,1);
    vel(j,2)=zprofile(j,2);
    vel(j,3)=zprofile(a*N2 + j,2);
    vel(j,4)=zprofile(b*N2 + j,2);
    vel(j,5)=zprofile(c*N2 + j,2);
    vel(j,6)=zprofile(d*N2 + j,2);
    vel(j,7)=zprofile(e*N2 + j,2);
    rho(j,1)=zprofile(j,1);
    rho(j,2)=zprofile(j,3);
    rho(j,3)=zprofile(a*N2 + j,3);
    rho(j,4)=zprofile(b*N2 + j,3);
    rho(j,5)=zprofile(c*N2 + j,3);
    rho(j,6)=zprofile(d*N2 + j,3);
    rho(j,7)=zprofile(e*N2 + j,3);
    pressure(j,1)=zprofile(j,1);
    pressure(j,2)=zprofile(j,4);
    pressure(j,3)=zprofile(a*N2 + j,4);
    pressure(j,4)=zprofile(b*N2 + j,4);
    pressure(j,5)=zprofile(c*N2 + j,4);
    pressure(j,6)=zprofile(d*N2 + j,4);
    pressure(j,7)=zprofile(e*N2 + j,4); 
    temp(j,1)=zprofile(j,1);
    temp(j,2)=zprofile(j,5);
    temp(j,3)=zprofile(a*N2 + j,5);
    temp(j,4)=zprofile(b*N2 + j,5);
    temp(j,5)=zprofile(c*N2 + j,5);
    temp(j,6)=zprofile(d*N2 + j,5);
    temp(j,7)=zprofile(e*N2 + j,5); 
end
figure(1);
plot (radius(rmin:N2,1),vel(rmin:N2,2),'cyan',radius(rmin:N2,2),vel(rmin:N2,3),'green',radius(rmin:N2,3),vel(rmin:N2,4),'blue',radius(rmin:N2,4),vel(rmin:N2,5),'black',radius(rmin:N2,5),vel(rmin:N2,6),'yellow',radius(rmin:N2,6),vel(rmin:N2,7),'red');
title ('u(x)');
xlabel ('r cm');
ylabel ('U cm/s');
grid ;
figure(2);
plot (radius(rmin:N2,1),rho(rmin:N2,2),'cyan',radius(rmin:N2,2),rho(rmin:N2,3),'green',radius(rmin:N2,3),rho(rmin:N2,4),'blue',radius(rmin:N2,4),rho(rmin:N2,5),'black',radius(rmin:N2,5),rho(rmin:N2,6),'yellow',radius(rmin:N2,6),rho(rmin:N2,7),'red');
title ('density');
xlabel ('r cm');
ylabel ('rho 10^-5 g/cm^3');
grid ;
figure(3);
plot (radius(rmin:N2,1),pressure(rmin:N2,2),'cyan',radius(rmin:N2,2),pressure(rmin:N2,3),'green',radius(rmin:N2,3),pressure(rmin:N2,4),'blue',radius(rmin:N2,4),pressure(rmin:N2,5),'black',radius(rmin:N2,5),rho(rmin:N2,6),'yellow',radius(rmin:N2,6),pressure(rmin:N2,7),'red');
title ('pressure');
xlabel ('r cm');
ylabel ('pressure');
grid ;
figure(4);
plot (radius(rmin:N2,1),temp(rmin:N2,2),'cyan',radius(rmin:N2,2),temp(rmin:N2,3),'green',radius(rmin:N2,3),temp(rmin:N2,4),'blue',radius(rmin:N2,4),temp(rmin:N2,5),'black',radius(rmin:N2,5),temp(rmin:N2,6),'yellow',radius(rmin:N2,6),temp(rmin:N2,7),'red');
title ('tempersture');
xlabel ('r cm');
ylabel ('T');
grid ;
